#!/bin/sh

cd /home/pi/git/rpi_stuff

#-----------------------------------------------------------
#               GPIO, RELE,  IP,   ID,  NAME
#-----------------------------------------------------------
 ./rele_turn.py  4    1      232   #01  rpiv-bagno
 ./rele_turn.py 17    1      35    #02  rpiv-rosaria
 ./rele_turn.py 27    1      34    #03  rpiv-francesco
 ./rele_turn.py 23    1      32    #06  rpiv-salone
 ./rele_turn.py 22    1      31    #04  rpiv-studio
#./rele_turn.py 18    1      000   #05  power-amp studio
#./rele_turn.py 24    1      232   #07  rpi-
#./rele_turn.py 25    1      232   #08  rpi-
#-----------------------------------------------------------

